[package]
name = "cura-wasm"
version = "2.0.0-alpha.0"
description = "Cura Engine for Web Assembly (WASM)"
license = "(MIT AND AGPL-3.0-only)"
license-file = "LICENSE"
repository = "https://github.com/cloud-cnc/cura-wasm.git"

[dependencies]
"cloud-cnc-bot/cura-engine" = "0.0.1-alpha.2"