# Continuous integration and delivery

name: Tests
on: push
jobs:
  test:
    name: Test (Node V${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14, 15]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install Modules
        run: sudo npm ci --unsafe-perm=true --allow-root
      - name: ESLint
        run: npm run lint
      - uses: paambaati/codeclimate-action@v2.6.0
        name: Test
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
        with:
          coverageCommand: sudo npm run coverage
      #Archive E2E videos
      - uses: actions/upload-artifact@v2
        name: Archive E2E videos
        if: ${{ always() }}
        with:
          name: e2e-videos
          path: ./tests/web/videos/

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - name: Install Modules
      run: sudo npm ci --unsafe-perm=true --allow-root
    - name: Build
      run: npm run build
    - name: Publish to NPM
      uses: pascalgn/npm-publish-action@1.2.0
      with:
        #See https://regexr.com/589ii for more information
        commit_pattern: "^v?(\\d+\\.\\d+\\.\\d+(?:-(?:alpha|beta)\\.\\d+)?)$"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}